---
name: Enhancement/Feature pull request
about: Enhancement/Feature pull request template.
labels: ["enhancement"]
assignees: ''

---

## Description

Please provide a brief description of the changes being made in this pull request.

## Related Issues

Please list any related issues or pull requests that are being resolved or addressed by this pull request.

Closes #issue_number

## Changes Made

Please describe the changes that were made in this pull request. Be as detailed as possible.

## Checklist

Please check off the following items before submitting your pull request:

- [ ] I have tested these changes thoroughly.
- [ ] I have reviewed my code for any potential errors or issues.
- [ ] I have followed the code style guidelines for this project.

## Additional Notes

Please provide any additional information or notes that may be helpful in reviewing this pull request.

## Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RyanLua/FluentAutoClicker?tab=coc-ov-file)
