project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /FluentAutoClicker/Strings/en-US/Resources.resw
    translation: /FluentAutoClicker/Strings/%locale%/Resources.resw
