name: Report a bug
description: Something is not working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! Your issue will be public, so **do not include any personal information**.
  - type: input
    id: version
    attributes:
      label: Fluent Auto Clicker version
      description: Version in app settings. Windows Settings > Apps > Installed apps > Fluent Auto Clicker
      placeholder: "1.0.0.0"
  - type: input
    id: windows-build
    attributes:
      label: Windows build number
      description: Window OS build. Windows Settings > System > About > Windows specifictions
      placeholder: "22631.4112"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Write a brief sentence about the bug
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: When I do this, that is supposed to happen
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened instead? If you have a screenshot or video, attach them.
      placeholder: When I do this, it instead does that